// <auto-generated />
using FeiraDaRoca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeiraDaRoca.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250805021050_RelacionamentoFeiranteProduto")]
    partial class RelacionamentoFeiranteProduto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("FeiraDaRoca.Models.Feirante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutoPrincipal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feirantes");
                });

            modelBuilder.Entity("FeiraDaRoca.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeiranteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeiranteId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("FeiraDaRoca.Models.Produto", b =>
                {
                    b.HasOne("FeiraDaRoca.Models.Feirante", "Feirante")
                        .WithMany("Produtos")
                        .HasForeignKey("FeiranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feirante");
                });

            modelBuilder.Entity("FeiraDaRoca.Models.Feirante", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
